### ISSUE TITLE
Window Resizes When Using Editor

### ISSUE THREAD

**Issue by sel6606** [flingengine/FlingEngine#129]
If the player attempts to edit a value for a transform in the editor window, typing any of the window resize shortcut keys will cause the window to resize.

Assuming we can detect when an editor field is being edited, we should temporarily disable the resize shortcuts until the player clicks off the editor window

**Comment by BenjaFriend** [comment]
It's too much work to determine if we are writting in an ImGUI window for now. The best thing is to just remove those keyboard shortcuts for the window and replace them with an IMGUI dropdown or something
