### ISSUE TITLE
Docker build test suite

### ISSUE THREAD

**Issue by BenjaFriend** [flingengine/FlingEngine#163]
It would be really nice to have a docker file that can build on Linux with your local changes, so that you can quickly test clang compilation and unit test suites.

**Comment by BenjaFriend** [comment]
We already have https://github.com/flingengine/FlingDockerBuild that can run in something like Jenkins, but that does a fresh clone/build every time. I want something that I can run locally in the actual source repo here to test local changes before pushing them up to staging.

**Comment by florianvazelle** [comment]
Hi, I'll work on it. I think I can do something good.

**Comment by BenjaFriend** [comment]
closing this because it's really unnecessary atm
