### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [flingengine/FlingEngine#174]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [Engine::Shutdown](https://github.com/flingengine/FlingEngine/blob/092c1506c2a024cdb8dcc0642fabc183d5f3db9f/FlingEngine/Core/src/Engine.cpp#L113 "Engine::Shutdown function")
- [MeshRenderer::Release](https://github.com/flingengine/FlingEngine/blob/092c1506c2a024cdb8dcc0642fabc183d5f3db9f/FlingEngine/Graphics/src/MeshRenderer.cpp#L30 "MeshRenderer::Release function")
- [VulkanApp::CleanupSwapChainResources](https://github.com/flingengine/FlingEngine/blob/092c1506c2a024cdb8dcc0642fabc183d5f3db9f/FlingEngine/Graphics/src/VulkanApp.cpp#L296 "VulkanApp::CleanupSwapChainResources function")

**Comment by BenjaFriend** [comment]
https://github.com/flingengine/FlingEngine/pull/176
