### ISSUE TITLE
Mesh Renderer Component 

### ISSUE THREAD

**Issue by BenjaFriend** [flingengine/FlingEngine#57]
With `Entt` integrated and the ability to load both models and textures, we can now create a `MeshRenderer` component. The `MeshRenderer` will be POD

- Pointer to the `Model` that it uses
- Pointer to the `Material` that should be uses

**Comment by axk4647** [comment]
A mesh should only contain the vertices and indices of the triangles and not the material. This way it will be easier to implement instance rendering or reuse meshes with different. I would suggest putting the material in the model.

**Comment by BenjaFriend** [comment]
The `material` should  be a seperate resource so that we can create all vulkan assets necessary on it and have them all be close to each other in memory. The `MeshRenderer` is just pointers to them. 

The model shouldn't care about what textures go on it, that's what the material is for. This will allow you to put on different materials to the same model.

**Comment by BenjaFriend** [comment]
Closed with #73
