### ISSUE TITLE
Graphics Pipeline Abstraction

### ISSUE THREAD

**Issue by axk4647** [flingengine/FlingEngine#68]
We should abstract the graphics pipeline so it will be easier to maintain our code down the road. Suggestions for implementation :

Base class :
GetDescriptorSetLayout()
GetDescriptorPool()
GetPipeline()
GetPipelineLayout()
GetPipelineBindPoint()

Child classes : GraphicsPipeline, (maybe) ComputePipeline

**Comment by BenjaFriend** [comment]
A lot of this will change with shader reflection you know :S

**Comment by BenjaFriend** [comment]
We can now create graphics pipelines and descriptor layouts based on their shaders with #87
